Vagrant.configure("2") do |config|
  nodes = [
    { name: "master1", ip: "192.168.56.11", role: "master1" },
    { name: "master2", ip: "192.168.56.12", role: "master2" },
    { name: "worker1", ip: "192.168.56.21", role: "worker" },
    { name: "worker2", ip: "192.168.56.22", role: "worker" },
    { name: "worker3", ip: "192.168.56.23", role: "worker" }
  ]

  config.vm.box = "generic/ubuntu2204"
  config.vm.synced_folder ".", "/vagrant", type: "rsync" # needed for script sharing

  nodes.each_with_index do |node, index|
    config.vm.define node[:name] do |node_config|
      node_config.vm.hostname = node[:name]
      node_config.vm.network "private_network", ip: node[:ip]

      node_config.vm.provider "qemu" do |qe|
        qe.arch = "x86_64"
        qe.machine = "q35"
        qe.cpu = "max"
        qe.memory = 2048
        qe.cpus = 2
        qe.net_device = "virtio-net-pci"
        qe.ssh_port = "50#{11 + index}"  # Dynamically set: 5011, 5012, ...
        qe.gui = true  # Show the display
      end

      node_config.vm.provision "shell", path: "../provision/common.sh"
      node_config.vm.provision "shell", path: "../provision/#{node[:role]}.sh", privileged: true
    end
  end
end
